### ISSUE TITLE
SPI.h should be included in MCP492X.h

### ISSUE THREAD

**Issue by lumostor** [michd/Arduino-MCP492X#1]
Great work, simple API, I like it. 

Almost worked the first try, beside the fact that SPI.h is not included from MCP492X.h. I think that it should be. As a "end user", it is natural to me that the library I use include the libraries it needs without having to think about it.

Other small thing in the example (in the readme.md) there is a small error:
        MCP492X myDac(PIN_SPI_CHIP_SELECT); 
should be 
        MCP492X myDac(PIN_SPI_CHIP_SELECT **_DAC**);

I didn't sent much time with those two issues, it was quite obvious.

Thanks

P.S. I am using it with STM32duino [https://github.com/rogerclarkmelbourne/Arduino_STM32](url)
        chip: stm32F103C8  on a Blue Pill board [http://wiki.stm32duino.com/index.php?title=Blue_Pill](url)(cheap chinese board)

**Comment by sash888** [comment]
Thank you for this @michd . It looks to be exactly what I also needed without me needing to figure out the coding. 

@lumostor thank you for your comments, I am relatively new to electronics, how do I include the SPI.h library? I have tried downloading the library from elsewhere however keep on receiving this error. I suspect the error is due to the missing SPI.h 

Thank you :)

_Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

In file included from C:\Users\Sashen Naicker\Documents\Arduino\DAC\SimpleDAC\SimpleDAC.ino:1:0:

MCP492X.h:83: error: 'SPISettings' does not name a type

     SPISettings _spiSettings;

     ^

exit status 1
'SPISettings' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences._

**Comment by lumostor** [comment]
Hi @sash888 

Just add the following line at the beginning of your .ino file.

#include <SPI.h>

The SPI library and it .h is bundled by default, you don't have to add the library.

**Comment by sash888** [comment]
Thank you @lumostor , I should have thought of that :)

It worked, but also had to put the line #include <SPI.h> in the MCP492X.h file for it to compile!

**Comment by lumostor** [comment]
@sash888  have you put the "#include <SPI.h>" line before or after the "#include <MCP492X.h>"

**Comment by sash888** [comment]
👍 Thank you, I have it after and now put it before and do not need the second #include <SPI.h> in the MCP492X.h 

I learnt something new about how libraries work thanks to you.

**Comment by lumostor** [comment]
You're welcome!

**Comment by philiparola** [comment]
@lumostor Same problem, thanks for posting the solution.  Perhaps file a pull request as well.
